<?xml version="1.0" encoding="utf-8"?><Database Name="DawnDB" Class="GameDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\Projects;Initial Catalog=DawnDB;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DawnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Loot" Member="Loots">
    <Type Name="Loot">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Loot_Entry" Member="LootEntries">
    <Type Name="LootEntry">
      <Column Name="LootId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AllowMultiple" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Chance" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Raid_TierData" Member="RaidTierDatas">
    <Type Name="RaidTierData">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RaidId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TierId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LootId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Health" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Attack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gold" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Raid_TierData_Loot" Member="RaidTierDataLoots">
    <Type Name="RaidTierDataLoot">
      <Column Name="TierDataId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Damage" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LootId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Spell" Member="Spells">
    <Type Name="Spell">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Method" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Parameter" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RarityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Unit" Member="Units">
    <Type Name="Unit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RarityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RaceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttributeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Attack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Defense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Perception" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Unit_Spell" Member="Unit_Spells">
    <Type Name="Unit_Spell">
      <Column Name="UnitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpellId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Parameter" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DisplayText" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TriggerText" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item_Spell" Member="ItemSpells">
    <Type Name="ItemSpell">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SpellId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Parameter" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="DisplayText" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TriggerText" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RarityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Attack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Defense" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Perception" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Raid" Member="Raids">
    <Type Name="Raid">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpellSlots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Duration" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
</Database>